rest:
  ssl: true
  host: ri.fdv.br
  port: 443
  nameSpace: /server

ui:
  ssl: true
  host: ri.fdv.br
  port: 443
  # Specify the public URL that this user interface responds to. This corresponds to the "dspace.ui.url" property in your backend's local.cfg.
  # SSR is only enabled when the client's "Host" HTTP header matches this baseUrl. The baseUrl is also used for redirects and SEO links (in robots.txt).
  baseUrl: https://ri.fdv.br
  # NOTE: Space is capitalized because 'namespace' is a reserved string in TypeScript
  nameSpace: /
  # The rateLimiter settings limit each IP to a 'max' of 500 requests per 'windowMs' (1 minute).
  rateLimiter:
    windowMs: 60000 # 1 minute
    max: 500 # limit each IP to 500 requests per windowMs
  # Trust X-FORWARDED-* headers from proxies (default = true)
  useProxies: true

defaultLanguage: pt_BR

# Theme Config
themes:
  - name: fdv
    prefetch: true
    headTags:
    - tagName: link
      attributes:
        rel: icon
        href: assets/fdv/images/favicons/favicon.ico
        sizes: any
    - tagName: link
      attributes:
        rel: icon
        href: assets/fdv/images/favicons/favicon.svg
        type: image/svg+xml
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: assets/fdv/images/favicons/apple-touch-icon.png
    - tagName: link
      attributes:
        rel: manifest
        href: assets/fdv/images/favicons/manifest.webmanifest